using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.IO;
using System.Reflection;

namespace AiApi.Demo
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);

            builder.Services.AddControllers();

            // 1. CONFIGURE SWAGGER TO READ THE "AI PROMPTS"
            builder.Services.AddSwaggerGen(c =>
            {
                // Find the XML file generated by the compiler
                var xmlFilename = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFilename);
                
                // Tell Swagger to include these comments in the final OpenAPI spec
                c.IncludeXmlComments(xmlPath);
            });

            var app = builder.Build();

            // 2. ENABLE SWAGGER UI
            app.UseSwagger();
            app.UseSwaggerUI();

            app.MapControllers();

            app.Run();
        }
    }
}
