<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\After.DomainModels\After.DomainModels.csproj" />
    <ProjectReference Include="..\After.BusinessLogic\After.BusinessLogic.csproj" />
    <ProjectReference Include="..\After.DataAccess\After.DataAccess.csproj" />
  </ItemGroup>

</Project>
